---
title: "Cockroach Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    navbar:
      - icon: fa-home
        href: https://prisrinivasan.github.io/p8105_final/
        align: left
    theme: journal
runtime: shiny
---

```{r, message = FALSE, warning = FALSE, include=FALSE, echo=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(leaflet)
library(shiny)
library(sf)
library(sp)
library(devtools)
library(rgdal)
library(rsconnect)
```

```{r, message = FALSE, warning = FALSE}
#dataset tidied on roach_data.Rmd for cleanliness
#loading dataframe saved from roach_data.Rmd
load("tidy_asthma_sf_ll.Rda")

#creating color palette
pal = colorQuantile("Reds", tidy_asthma_sf_ll$homes_with_cockroaches, n = 6)
pal_a = colorQuantile("Reds", tidy_asthma_sf_ll$public_school_children_5_14_yrs_old_with_asthma, n = 6)
```

Column {.sidebar}
-----------------------------------------------------------------------
We created these interactive maps to show the spread of cockroaches and rate of asthma over neighborhoods in New York City.

The variable `homes_with_cockroaches` indicates the percentage of homes in each neighborhood that have seen a cockroach every day for a month.

The rate of asthma is shown as a number per 1,000 in each neighborhood among public school children ages 5-14.

#### Use the dropdown, checkboxes, and slider below to visualize roaches and rate in New York.

```{r}
year = as.character(c("2011", "2014"))

#selectInput for year choices
selectInput(
  "year", 
  label = h5("Select Year"),
  choices = year,
  selected = "2011")

#creating vector with borough names for choices
borough = c("Bronx", "Brooklyn", "Manhattan", "Queens", "Staten Island")

#function for borough choices
func = function(x, borough) {
  if (x %in% borough) {
    TRUE} else{
      FALSE}}

#checkboxes
checkboxGroupInput(
  "borough", 
  label = h5("Choose borough"),
  choices = borough,
  selected = borough)


sliderInput(
  "roach_range", 
  label = h5("Choose a range of homes with cockroaches"), 
  min = 0, max = 50, value = c(0, 50), step = 0.2, post  = "%")

hr()
```


Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Home Alone 6: Roach Invasion
```{r}
mapinput = reactive({
  
  tidy_asthma_sf_ll %>%
    mutate(borough = map(borough, func, input$borough),
           roach_label = str_c("Homes with Cockroaches: ", homes_with_cockroaches, "% \n, Neighborhood: ", uhf_neigh)) %>% 
    filter(borough == TRUE,
           time_period == input$year,
           between(homes_with_cockroaches, input$roach_range[1], input$roach_range[2]))
  
})

renderLeaflet({
  
  mapinput() %>% 
    leaflet() %>%
    addProviderTiles("CartoDB.Positron") %>%
    addPolygons(stroke = TRUE,
                weight = 2,
                opacity = 1,
                color = ~pal(homes_with_cockroaches),
                fillOpacity = 0.8,
                smoothFactor = 0.2,
                highlight = highlightOptions(weight = 3,
                                             color = "white",
                                             bringToFront = TRUE),
                label = ~roach_label) %>% 
    addLegend("bottomright",
              pal = pal,
              values = ~homes_with_cockroaches,
              title = "Percent of Homes with Cockroaches",
              opacity = 1,
              labFormat = function(type, cuts, p) {
                n = length(cuts)
                paste0(round(cuts, 1)[-n], " &ndash; ", round(cuts, 1)[-1], "%")
                })
  
  })
```


### Home Alone 7: Asthma Attack
```{r}
mapinput_2 = reactive({
  
  tidy_asthma_sf_ll %>%
    mutate(borough = map(borough, func, input$borough),
           roach_label = str_c("Asthma Rate (per 1,000): ", public_school_children_5_14_yrs_old_with_asthma, "\n, Neighborhood: ", uhf_neigh)) %>% 
    filter(borough == TRUE,
           time_period == input$year)
  
})
renderLeaflet({
  
  mapinput_2() %>% 
    leaflet() %>%
    addProviderTiles("CartoDB.Positron") %>%
    addPolygons(stroke = TRUE,
                weight = 2,
                opacity = 1,
                color = ~pal_a(public_school_children_5_14_yrs_old_with_asthma),
                fillOpacity = 0.8,
                smoothFactor = 0.2,
                highlight = highlightOptions(weight = 3,
                                             color = "white",
                                             bringToFront = TRUE),
                label = ~roach_label) %>% 
    addLegend("bottomright",
              pal = pal_a,
              values = ~public_school_children_5_14_yrs_old_with_asthma,
              title = "Asthma Count (per 1,000)",
              opacity = 1,
              labFormat = function(type, cuts, p) {
                n = length(cuts)
                paste0(round(cuts)[-n], " &ndash; ", round(cuts)[-1])
                }
              )
  
  })
```
